<template>
    <div>
        <h4>AUTORIZACIONES Y ACUERDOS LEGALES</h4>

        <p class="fw-bold">Autorización</p>
        <p>La autorización de la solicitud es el último paso que debe completarse antes de remitirla a La Fundación Rotaria. Repasa la información ingresada en cada paso y proporciona tu autorización más abajo. Dependiendo de tu función, es posible que debas autorizar la solicitud más de una vez.</p>
        <p>Cuando se bloqueó la solicitud en el paso previo, se enviaron correos electrónicos a los líderes de club o distrito que deben autorizarla. En este paso podrás ver quiénes dieron ya su autorización.</p>

        <p class="fw-bold">Autorización del contacto principal</p>

        <pre>
            Global Grant Agreement - to be authorized by the primary contacts and club presidents (or DRFC chairs if district-sponsored)

            This Global Grant Agreement (Agreement) is entered into by The Rotary Foundation of Rotary International (TRF) and the grant sponsors (Sponsors). In consideration of receiving this Rotary Foundation Global Grant (Grant) from TRF, the Sponsors agree that:

            1. All information contained in this application is, to the best of our knowledge, true and accurate.
            2. We have read the Terms and Conditions for Rotary Foundation Global Grants (Terms and Conditions) and will adhere to all policies therein.
            3. The Sponsors shall defend, indemnify, and hold harmless Rotary International (RI) and TRF, including their respective directors, trustees, officers, committee members, employees, agents, associate foundations and representatives (collectively Rotary), from and against all claims, including but not limited to claims of subrogation, demands, actions, damages, losses, costs, liabilities, expenses (including reasonable attorney’s fees and other legal expenses), awards, judgments, and fines asserted against or recovered from Rotary arising out of any act, conduct, omission, negligence, misconduct, or unlawful act (or act contrary to any applicable governmental order or regulation) resulting directly or indirectly from a Sponsor’s and/or participant’s involvement in grant-funded activities, including all travel related to the grant.
            4. The failure of the parties to comply with the terms of this Agreement due to an act of God, strike, government regulation, war, fire, riot, civil unrest, hurricane, earthquake, or other natural disasters, acts of public enemies, curtailment of transportation facilities, political upheavals, civil disorders, outbreak of infectious disease or illness, acts of terrorism, or any similar cause beyond the control of the parties shall not be deemed a breach of this Agreement. In such an event, the Agreement shall be deemed terminated and the Sponsors shall refund to TRF all unexpended global grant funds within 30 days of termination.
            5. TRF’s entire responsibility is expressly limited to payment of the total financing amount. TRF does not assume any further responsibility in connection with this grant.
            6. TRF reserves the right to cancel the grant and/or this Agreement without notice upon the failure of either or both of the Sponsors to abide by the terms set forth in this Agreement and the Terms and Conditions. Upon cancellation, TRF shall be entitled to a refund from the Sponsors of any global grant funds, including any interest earned, that have not been expended.
            7. The laws of the State of Illinois, USA, without reference to its conflicts of laws principles, shall govern all matters arising out of or relating to this Agreement, including, without limitation, its interpretation, construction, performance, and enforcement.
            8. Any legal action brought by either party against the other party arising out of or relating to this Agreement must be brought in either, the Circuit Court of Cook County, State of Illinois, USA or the Federal District Court for the Northern District of Illinois, USA. Each party consents to the exclusive jurisdiction of these courts, and their respective appellate courts for the purpose of such actions. Nothing herein prohibits a party that obtains a judgment in either of the designated courts from enforcing the judgment in any other court. Notwithstanding the foregoing, TRF may also bring legal action against Sponsors and/or individuals traveling on grant funds in any court with jurisdiction over them.
            9. This Agreement binds and benefits the parties and their respective administrators, legal representatives, and permitted successors and assigns.
            10. If any provision of this Agreement is determined to be illegal, invalid or unenforceable, the remaining provisions of this Agreement shall remain in full force and effect.
            11. Sponsors may not assign any of their rights under this Agreement except with the prior written consent of TRF. Sponsors may not delegate any performance under this Agreement without the prior written consent of TRF. Any purported assignment of a Sponsor’s rights or delegation of performance without TRF’s prior written consent is void.
            12. TRF may assign some or all of its rights under this Agreement to an associate foundation of TRF. TRF may delegate any performance under this Agreement to an associate foundation. Any other purported assignment of TRF’s rights or delegation of performance without the Sponsors’ prior written consent is void.
            13. Sponsors will comply with all economic and trade sanctions, including those implemented by the Office of Foreign Assets Control (OFAC) of the United States Department of Treasury, and will ensure that they do not support or promote violence, terrorist activity or related training, or money laundering.
            14. This Agreement constitutes the final agreement between the parties. No amendment or waiver of any provision of this Agreement shall be effective unless it is in the form of a writing signed by the parties.
            15. Rotary may use information contained in this application and subsequent reports for promotional purposes, such as in Rotary magazine, in Rotary Leader, on rotary.org and on social media. For any and all photographs submitted with any application or follow-up report, the Sponsor hereby grants to Rotary an unlimited, perpetual, worldwide right and license to use, modify, adapt, publish, and distribute the photograph(s) in any media now known or hereafter devised, including but not limited to, in Rotary publications, advertisements, and Websites and on social media channels. The Sponsor represents and warrants that (a) each adult appearing in the photograph(s) has given her/his/their unrestricted written consent to the Sponsor to photograph them and to use and license their likeness, including licensing the photograph(s) to third parties, (b) the parent or guardian of each child under age 18 or each person who lacks legal capacity appearing in the photograph(s) has given unrestricted written consent to the Sponsor to photograph the child or individual and to use and license their likenesses, including licensing the photograph(s) to third parties, and (c) it is the copyright owner of the photograph(s) or that the copyright owner of the photograph(s) has given the Sponsor the right to license or sublicense the photograph(s) to Rotary.
            16. Privacy is important to Rotary and any personal data that the Sponsor shares with Rotary will only be used for official Rotary business. The Sponsor should minimize the personal data of Grant beneficiaries that it shares with TRF to only personal data that TRF specifically requests. Personal data that is shared with TRF will be used to enable the Sponsor’s participation in this Grant process, to facilitate the Sponsor’s Grant experience and for reporting purposes. Personal data provided to TRF may be transferred to Rotary service providers (for example, affiliated entities) to assist Rotary in planning Grant-related activities. By applying for a grant, the Sponsor may receive information about the Grant and supplementary services via email. For further information about how Rotary uses personal data, please contact privacy@rotary.org. Personal data provided to TRF or collected on this form is subject to Rotary’s Privacy Policy.
            17. The Sponsors agree to share information on best practices when asked, and TRF may provide their contact information to other Rotary members who may wish advice on implementing similar activities.
            18. The Sponsors will ensure that all individuals traveling on grant funds have been informed of the travel policies stated in the Terms and Conditions and have been made aware that they are responsible for obtaining travel insurance.
            19. To the best of our knowledge and belief, all relationships between grant committee members, district officers, and other members of the sponsor clubs or districts and any scholarship recipients, cooperating organizations, project vendors, or other individuals or organizations that will benefit from the grant have been disclosed in this application. Except as disclosed here, neither we nor any person with whom we have or had a personal or business relationship will benefit or intends to benefit from Rotary Foundation grant funds or have any interest that may represent a potential conflicting interest. A conflict of interest occurs when someone is in a position to make or influence a decision about a grant or scholarship that could benefit them, their family, their business, or an entity in which they serve in a paid or voluntary leadership or advisory position.

        </pre>
    </div>
</template>
